### ISSUE TITLE
Add support for creating links to binaries

### ISSUE THREAD

**Issue by agateau** [agateau/clyde#22]
Some apps do not lend themselves to the classic bin, lib, share separation. For example the Windos versions of icoutils or Node 16.

In this case we need to install the app files in its own directory, and create links to the binaries.

These links can be symbolic links on Linux and macOS, but they must be .cmd files on Windows.

The links must be added to the installed DB.

Here is a possible way to express this in Clyde .yaml package.

```yaml
install:
  any-windows:
    strip: 0
    files:
      bin/foo.exe: opt/foo/bin/foo.exe
      bin/zlib1.dll: opt/foo/bin/zlib1.dll
    binlinks:
      opt/foo/bin/foo.exe: bin/foo
```
