### ISSUE TITLE
Add a ${archive_name} variable

### ISSUE THREAD

**Issue by agateau** [agateau/clyde#65]
Having a variable containing the archive name would be useful for projects like miniserve, whose releases are the binary. This would simplify the `installs` definition. Instead of this:

```yaml
installs:
  0.20.0:
    x86_64-windows:
      strip: 0
      files:
        miniserve-v0.20.0-x86_64-pc-windows-msvc.exe: bin/miniserve.exe
    x86_64-linux:
      strip: 0
      files:
        miniserve-v0.20.0-x86_64-unknown-linux-musl: bin/miniserve
```

We would be able to write this:

```yaml
installs:
  0.20.0:
    any-any:
      strip: 0
      files:
        ${archive_name}: bin/miniserve${exe_ext}
```
